# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_detect', [dirname(__file__)])
        except ImportError:
            import _detect
            return _detect
        if fp is not None:
            try:
                _mod = imp.load_module('_detect', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _detect = swig_import_helper()
    del swig_import_helper
else:
    import _detect
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _detect.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _detect.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _detect.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _detect.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _detect.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _detect.SwigPyIterator_equal(self, x)

    def copy(self):
        return _detect.SwigPyIterator_copy(self)

    def next(self):
        return _detect.SwigPyIterator_next(self)

    def __next__(self):
        return _detect.SwigPyIterator___next__(self)

    def previous(self):
        return _detect.SwigPyIterator_previous(self)

    def advance(self, n):
        return _detect.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _detect.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _detect.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _detect.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _detect.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _detect.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _detect.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _detect.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class vectori(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vectori, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vectori, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _detect.vectori_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _detect.vectori___nonzero__(self)

    def __bool__(self):
        return _detect.vectori___bool__(self)

    def __len__(self):
        return _detect.vectori___len__(self)

    def __getslice__(self, i, j):
        return _detect.vectori___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _detect.vectori___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _detect.vectori___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _detect.vectori___delitem__(self, *args)

    def __getitem__(self, *args):
        return _detect.vectori___getitem__(self, *args)

    def __setitem__(self, *args):
        return _detect.vectori___setitem__(self, *args)

    def pop(self):
        return _detect.vectori_pop(self)

    def append(self, x):
        return _detect.vectori_append(self, x)

    def empty(self):
        return _detect.vectori_empty(self)

    def size(self):
        return _detect.vectori_size(self)

    def swap(self, v):
        return _detect.vectori_swap(self, v)

    def begin(self):
        return _detect.vectori_begin(self)

    def end(self):
        return _detect.vectori_end(self)

    def rbegin(self):
        return _detect.vectori_rbegin(self)

    def rend(self):
        return _detect.vectori_rend(self)

    def clear(self):
        return _detect.vectori_clear(self)

    def get_allocator(self):
        return _detect.vectori_get_allocator(self)

    def pop_back(self):
        return _detect.vectori_pop_back(self)

    def erase(self, *args):
        return _detect.vectori_erase(self, *args)

    def __init__(self, *args):
        this = _detect.new_vectori(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _detect.vectori_push_back(self, x)

    def front(self):
        return _detect.vectori_front(self)

    def back(self):
        return _detect.vectori_back(self)

    def assign(self, n, x):
        return _detect.vectori_assign(self, n, x)

    def resize(self, *args):
        return _detect.vectori_resize(self, *args)

    def insert(self, *args):
        return _detect.vectori_insert(self, *args)

    def reserve(self, n):
        return _detect.vectori_reserve(self, n)

    def capacity(self):
        return _detect.vectori_capacity(self)
    __swig_destroy__ = _detect.delete_vectori
    __del__ = lambda self: None
vectori_swigregister = _detect.vectori_swigregister
vectori_swigregister(vectori)

class vectorf(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vectorf, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vectorf, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _detect.vectorf_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _detect.vectorf___nonzero__(self)

    def __bool__(self):
        return _detect.vectorf___bool__(self)

    def __len__(self):
        return _detect.vectorf___len__(self)

    def __getslice__(self, i, j):
        return _detect.vectorf___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _detect.vectorf___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _detect.vectorf___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _detect.vectorf___delitem__(self, *args)

    def __getitem__(self, *args):
        return _detect.vectorf___getitem__(self, *args)

    def __setitem__(self, *args):
        return _detect.vectorf___setitem__(self, *args)

    def pop(self):
        return _detect.vectorf_pop(self)

    def append(self, x):
        return _detect.vectorf_append(self, x)

    def empty(self):
        return _detect.vectorf_empty(self)

    def size(self):
        return _detect.vectorf_size(self)

    def swap(self, v):
        return _detect.vectorf_swap(self, v)

    def begin(self):
        return _detect.vectorf_begin(self)

    def end(self):
        return _detect.vectorf_end(self)

    def rbegin(self):
        return _detect.vectorf_rbegin(self)

    def rend(self):
        return _detect.vectorf_rend(self)

    def clear(self):
        return _detect.vectorf_clear(self)

    def get_allocator(self):
        return _detect.vectorf_get_allocator(self)

    def pop_back(self):
        return _detect.vectorf_pop_back(self)

    def erase(self, *args):
        return _detect.vectorf_erase(self, *args)

    def __init__(self, *args):
        this = _detect.new_vectorf(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _detect.vectorf_push_back(self, x)

    def front(self):
        return _detect.vectorf_front(self)

    def back(self):
        return _detect.vectorf_back(self)

    def assign(self, n, x):
        return _detect.vectorf_assign(self, n, x)

    def resize(self, *args):
        return _detect.vectorf_resize(self, *args)

    def insert(self, *args):
        return _detect.vectorf_insert(self, *args)

    def reserve(self, n):
        return _detect.vectorf_reserve(self, n)

    def capacity(self):
        return _detect.vectorf_capacity(self)
    __swig_destroy__ = _detect.delete_vectorf
    __del__ = lambda self: None
vectorf_swigregister = _detect.vectorf_swigregister
vectorf_swigregister(vectorf)

class vectoru(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vectoru, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vectoru, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _detect.vectoru_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _detect.vectoru___nonzero__(self)

    def __bool__(self):
        return _detect.vectoru___bool__(self)

    def __len__(self):
        return _detect.vectoru___len__(self)

    def __getslice__(self, i, j):
        return _detect.vectoru___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _detect.vectoru___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _detect.vectoru___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _detect.vectoru___delitem__(self, *args)

    def __getitem__(self, *args):
        return _detect.vectoru___getitem__(self, *args)

    def __setitem__(self, *args):
        return _detect.vectoru___setitem__(self, *args)

    def pop(self):
        return _detect.vectoru_pop(self)

    def append(self, x):
        return _detect.vectoru_append(self, x)

    def empty(self):
        return _detect.vectoru_empty(self)

    def size(self):
        return _detect.vectoru_size(self)

    def swap(self, v):
        return _detect.vectoru_swap(self, v)

    def begin(self):
        return _detect.vectoru_begin(self)

    def end(self):
        return _detect.vectoru_end(self)

    def rbegin(self):
        return _detect.vectoru_rbegin(self)

    def rend(self):
        return _detect.vectoru_rend(self)

    def clear(self):
        return _detect.vectoru_clear(self)

    def get_allocator(self):
        return _detect.vectoru_get_allocator(self)

    def pop_back(self):
        return _detect.vectoru_pop_back(self)

    def erase(self, *args):
        return _detect.vectoru_erase(self, *args)

    def __init__(self, *args):
        this = _detect.new_vectoru(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _detect.vectoru_push_back(self, x)

    def front(self):
        return _detect.vectoru_front(self)

    def back(self):
        return _detect.vectoru_back(self)

    def assign(self, n, x):
        return _detect.vectoru_assign(self, n, x)

    def resize(self, *args):
        return _detect.vectoru_resize(self, *args)

    def insert(self, *args):
        return _detect.vectoru_insert(self, *args)

    def reserve(self, n):
        return _detect.vectoru_reserve(self, n)

    def capacity(self):
        return _detect.vectoru_capacity(self)
    __swig_destroy__ = _detect.delete_vectoru
    __del__ = lambda self: None
vectoru_swigregister = _detect.vectoru_swigregister
vectoru_swigregister(vectoru)

class npddetect(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, npddetect, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, npddetect, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _detect.new_npddetect(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _detect.delete_npddetect
    __del__ = lambda self: None

    def load(self, modelpath):
        return _detect.npddetect_load(self, modelpath)

    def gridScan(self, I, width, height, stepR=0.5, thresR=0.0):
        return _detect.npddetect_gridScan(self, I, width, height, stepR, thresR)

    def pyDetect(self, I, width, height):
        return _detect.npddetect_pyDetect(self, I, width, height)

    def detect(self, *args):
        return _detect.npddetect_detect(self, *args)

    def prescandetect(self, I, width, height, stepR=0.5, thresR=0.0):
        return _detect.npddetect_prescandetect(self, I, width, height, stepR, thresR)

    def getXs(self):
        return _detect.npddetect_getXs(self)

    def getYs(self):
        return _detect.npddetect_getYs(self)

    def getSs(self):
        return _detect.npddetect_getSs(self)

    def getScores(self):
        return _detect.npddetect_getScores(self)

    def getX(self):
        return _detect.npddetect_getX(self)

    def getY(self):
        return _detect.npddetect_getY(self)

    def getS(self):
        return _detect.npddetect_getS(self)

    def getScore(self):
        return _detect.npddetect_getScore(self)

    def draw(self, arg2):
        return _detect.npddetect_draw(self, arg2)
npddetect_swigregister = _detect.npddetect_swigregister
npddetect_swigregister(npddetect)

# This file is compatible with both classic and new-style classes.


